### ISSUE TITLE
Training file missing!

### ISSUE THREAD

**Issue by ltp1995** [yakazimir/semantic_fragments#1]
Dear authors, your trainning file  **train_snli_mnli.sh** is missing, which should exist under **./scripts/** folder,  please update your repository if it is convenient.

**Comment by yakazimir** [comment]
Thanks for your message. You can find it under `generate_challenge/data/snli_mnli_train.zip` (sorry for the lack of documentation). It's built from the [GLUE](https://gluebenchmark.com/leaderboard) version of SNLI+MNLI (as detailed in the script).

**Comment by yakazimir** [comment]
Thanks for your message. The script should be there now (thanks for catching that).
